language: android
jdk: oraclejdk8
sudo: enabled

android:
  components:
    -tools
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-22
    - android-24
    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository
    
script:
    - sudo chmod +x ./gradlew
    - ./gradlew check
